### ISSUE TITLE
Undefined is not an object (evaluating '_reactNative.Image.resizeMode.stretch')

### ISSUE THREAD

**Issue by albemala** [madsleejensen/react-native-image-capinsets#15]
Hello,

When using React Native 0.56 I get this error:

`Undefined is not an object (evaluating '_reactNative.Image.resizeMode.stretch')`

It looks like usage of Image.resizeMode.stretch enum has been removed in React Native 0.56, replaced by string usage only ("stretch"). 
Source: https://github.com/facebook/react-native/commit/870775ee738e9405c6545500f9a637df9b513a02

Would it be possible to replace the enum with the string for both iOS and Android please?

albemala

**Comment by ludashen** [comment]
me too

**Comment by ludashen** [comment]
i have the same problem

**Comment by madsleejensen** [comment]
ah thanks for letting me know, would be happy to accept a pr with fix :)

**Comment by yurykorzun** [comment]
> ah thanks for letting me know, would be happy to accept a pr with fix :)

I pushed a pull request to fix the issue

**Comment by madsleejensen** [comment]
Thanks @yurykorzun for the PR, its been published in 0.5.0 💯
