### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by thelordoftheboards** [madsleejensen/react-native-image-capinsets#2]
Since cap insets are natively supported on android the implementation on that platform should be more or less straightforward. How about iOS support, what are the options?

**Comment by madsleejensen** [comment]
Im abit confused when you say this is natively supported on Android? This is a library to enable similar implementation of `capInsets` for the <Image /> component as described here: https://facebook.github.io/react-native/docs/image.html for Android.

**Comment by thelordoftheboards** [comment]
I am sorry I asked the question in a confusing way. Let me try this again.

is `react-native-image-capinsets` supported on iOS and how hard would it be to add such support if it is not?

**Comment by madsleejensen** [comment]
Ah yes :) react-native supports capInsets out of the box on the <Image /> component, i created a light high-order component for this library which simply wraps around the <Image /> see index.ios.js . If you are only building for iOS you properly shouldnt use this library .

**Comment by thelordoftheboards** [comment]
Awesome! I am definitely looking towards building for both iOS and Android. Thank you! I will close this issue :)
