### ISSUE TITLE
Scrolling issue on Android

### ISSUE THREAD

**Issue by phoenix214** [madsleejensen/react-native-image-capinsets#4]
![screenshot_1489084213](https://cloud.githubusercontent.com/assets/12434469/23764731/ee1a1c56-0541-11e7-9d54-beaba247c179.png)

I'm using this package for adding bubble image on chat-style app, embedding it in ListView
It works fine on iOS version, and in Android before scrolling up.
But when I scrolled it up, the images' sizes are changed.
Can you please help me to fix this issue?

Regards.

**Comment by guanpy** [comment]
I met the same problem, It's the **cache**  led to this, I have to comment the **cache** code ,Unless find a solution.
```
public class RCTImageCapInsetView extends ImageView {
...
   final RCTImageCache cache = RCTImageCache.getInstance();
   if (cache.has(key)) {
            setBackgroundDrawable(cache.get(key));
            return;
        }
...
```

**Comment by pawlowskim** [comment]
I can confirm, you shouldn't use cache.

**Comment by godness84** [comment]
I submitted a PR to fix this problem. Give it a try updating your `package.json` with:
`
"react-native-image-capinsets": "godness84/react-native-image-capinsets#fix-issue-4"
`

and let me know if it works even for you. Thanks.

**Comment by pawlowskim** [comment]
Praise the @godness84 :) You have saved me few days of work probably :) Wish you have post it 8h ago so I could save one more day. Thanks a lot. 

BTW. It works :)

**Comment by godness84** [comment]
@madsleejensen, I think that now it's possible to close this issue :)

**Comment by madsleejensen** [comment]
thanks for the help @godness84  👍
