### ISSUE TITLE
I have question, seems i missing something. Why ninepatch lines displayed?

### ISSUE THREAD

**Issue by maxim-c** [madsleejensen/react-native-image-capinsets#9]
android
![image](https://user-images.githubusercontent.com/6708097/29814632-b54f9d04-8cb6-11e7-92e4-dc16480c2f1a.png)

why 9patch lines displayed?

**Comment by Kishanjvaghela** [comment]
@maxim-c Did you solve this?

**Comment by maxim-c** [comment]
like i understand library generate ninepatch image by provided capInsets object, so no need provide ninepatch image - just use simple images.

**Comment by madsleejensen** [comment]
yes the image should not contain the ninepatch lines :)
